vision_park/accounts/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/', views.profile_add_car, name='profile'),
    path('profile/delete/<int:pk>/', views.profile_action, name='profile_action'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                          success_url='/auth/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

vision_park/finance/urls.py
from django.urls import path
from . import views

app_name = "finance"

urlpatterns = [
    path('payments-user/', views.payments_user, name='payments_user'),
    path('payment-preview/<int:session_id>/', views.payment_preview, name='payment_preview'),
    path('payment-confirm/<int:session_id>/', views.payment_confirm, name='payment_confirm'),
    path('tariffs/', views.tariffs, name='tariffs'),
    path('tariff-add/', views.tariff_add, name='tariff_add'),
    path('tariff-complete/<int:tariff_id>', views.tariff_complete, name='tariff_complete'),
]

vision_park/parking_area/urls.py
from django.urls import path
from . import views

app_name = 'parking_area'

urlpatterns = [
    path('', views.index, name='parking_area'),
    path('get_parking_spaces/', views.get_parking_spaces, name='get_parking_spaces'),
]

vision_park/recognize/urls.py
from django.urls import path
from . import views

app_name = "recognize"

urlpatterns = [
    path("main", views.main, name="main"),
    path("upload_in", views.upload_in, name="upload_in"),
    path("result_in", views.create_parking_session, name="result_in"),
    path("session_view", views.session_view, name="session_view"),
    path('session_action/<int:pk>/', views.session_action, name='session_action'),
    path("download_csv", views.download_csv, name="download_csv"),
]

vision_park/vision_park/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_control
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve

from . import views
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('auth/', include('accounts.urls')),
    path('parking_area/', include('parking_area.urls')),
    path('recognize/', include('recognize.urls')),
    path('finance/', include('finance.urls')),
] + static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve)) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vision_park/vision_park/views.py
from django.shortcuts import render


def main(request):
    return render(request, "vision_park/main.html")

vision_park/vision_park/templates/vision_park/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta
            name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
    >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://fonts.googleapis.com/css?family=DM Sans" rel="stylesheet"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    {% load static %}
    <link rel="icon" href="{% static 'img/logo-remove-bg.ico' %}" type="image/x-icon">

    <!--    <link rel="stylesheet" href="{% static 'css/style.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}?v=1"/>
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}"/>
    <link rel="icon" href="{% static 'vision_park/favicon.png' %}"/>

    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<main class="d-flex flex-nowrap">


    <div class="sidebar d-flex flex-column flex-shrink-0 text-bg-custom">
        <a href="/" class="mx-auto mb-1 text-white text-decoration-none"
           style="display: flex; align-items: center; gap: 7px">
            <img src="{% static 'img/logo-remove-bg.png' %}" title="Vision Park Team" alt="Vision Park Team"
                 style="max-width: 60px; width: 100%; background: white; padding: 5px; border-radius: 30px"/>
            <span id="team-long" class="ms-1 fs-5" style="font-weight: bold" title="Vision Park Team">Vision Park Team</span>
        </a>

        <hr style="margin: 10px 0 10px 0;"/>
        <ul style="display: flex; flex-direction: column; gap: 10px; padding: 10px 0">
            <li>
                <a class="nav-link text-white"
                   href="{% url 'parking_area:parking_area' %}">
                    <i class='bx bx-car'></i>
                    <span class="nav-item">Parking</span>
                </a>
            </li>
            {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <li>
                <a class="nav-link text-white"
                   href="{% url 'recognize:main' %}">
                    <i class='bx bx-camera-movie'></i>
                    <span class="nav-item">Car Recognize</span>
                </a>
            </li>
            <li>
                <a class="nav-link text-white"
                   href="{% url 'finance:tariffs' %}">
                    <i class='bx bx-money-withdraw'></i>
                    <span class="nav-item">Tariffs</span>
                </a>
            </li>
            {% else %}

            <li>
                <a class="nav-link text-white"
                   href="{% url 'accounts:profile' %}">
                    <i class='bx bx-user-circle'></i>
                    <span class="nav-item">Profile</span>
                </a>
            </li>

            <li>
                <a class="nav-link text-white"
                   href="{% url 'finance:payments_user' %}">
                    <i class='bx bx-money'></i>
                    <span class="nav-item">Finance</span>
                </a>
            </li>

            {% endif %}

            <li>
                <a class="nav-link text-white"
                   href="{% url 'accounts:logout' %}">
                    <i class='bx bx-log-out'></i>
                    <span class="nav-item">Logout</span>
                </a>
            </li>
            {% else %}
            <li>
                <a class="nav-link text-white"
                   href="{% url 'accounts:login' %}">
                    <i class='bx bx-log-in'></i>
                    <span class="nav-item">Login</span>
                </a>
            </li>

            <li>
                <a class="nav-link text-white"
                   href="{% url 'accounts:register' %}">
                    <i class='bx bx-id-card'></i>
                    <span class="nav-item">Register</span>
                </a>
            </li>
            {% endif %}
        </ul>
        <hr style="margin: 10px 0 10px 0;"/>
        <div style="display: flex; margin-left: 10px">

            {% if user.is_authenticated %}
            <strong style="color: white; font-size: 18px">{{user.username}}</strong>
            {% endif %}
        </div>
    </div>

    <div class="b-example-vr">
    </div>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
</main>
</body>
</html>

vision_park/vision_park/templates/vision_park/main.html
{% extends 'vision_park/base.html' %}

{% block title %}
Ace of Base
{% endblock %}

{% block content %}
{% load static %}
<div class="container mt-3 text-center">

<h2 class="title is-2">ACE OF BASE</h2>

    {% for message in messages %}
        <h3 class="justify-content-center" style="margin-left: 0px; margin-bottom: 30px"> {{ message }}</h3>
    {% endfor %}

    {% if user.is_authenticated %}
    <div class="quote" style="margin-top: 30px; text-align: center;" itemscope="" itemtype="http://schema.org/CreativeWork" >
        <h3 class="title is-3">Welcome {{ request.user }} in Vision Park!</h3>
    </div>
    {% else %}
    <div class="quote" style="margin-top: 30px; text-align: center;" itemscope="" itemtype="http://schema.org/CreativeWork">
        <h3 class="title is-3">Welcome!</h3>
        <h4 class="title is-4">To start using <b>Vision Parking</b>, You must log in to your account!</h4>
    </div>
    {% endif %}


    <img style="margin-top: 30px;" src="{% static 'img/logo-compressed1.jpg' %}" alt="Main Logo" class="rounded-logo">
</div>

{% endblock %}