vision_park/finance/urls.py
from django.urls import path
from . import views

app_name = "finance"

urlpatterns = [
    path('payments-user/', views.payments_user, name='payments_user'),
    path('payment-preview/<int:session_id>/', views.payment_preview, name='payment_preview'),
    path('payment-confirm/<int:session_id>/', views.payment_confirm, name='payment_confirm'),
    path('tariffs/', views.tariffs, name='tariffs'),
    path('tariff-add/', views.tariff_add, name='tariff_add'),
    path('tariff-complete/<int:tariff_id>', views.tariff_complete, name='tariff_complete'),
]

vision_park/recognize/urls.py
from django.urls import path
from . import views

app_name = "recognize"

urlpatterns = [
    path("main", views.main, name="main"),
    path("upload_in", views.upload_in, name="upload_in"),
    path("result_in", views.create_parking_session, name="result_in"),
    path("session_view", views.session_view, name="session_view"),
    path('session_action/<int:pk>/', views.session_action, name='session_action'),
    path("download_csv", views.download_csv, name="download_csv"),
]

vision_park/vision_park/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_control
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve

from . import views
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('auth/', include('accounts.urls')),
    path('parking_area/', include('parking_area.urls')),
    path('recognize/', include('recognize.urls')),
    path('finance/', include('finance.urls')),
] + static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve)) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vision_park/recognize/models.py
from django.db import models

from accounts.models import CustomUser
from finance.models import Pricing
from parking_area.models import ParkingSpace


class Car(models.Model):
    license_plate = models.CharField(max_length=16, unique=True)
    owner = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.CASCADE, related_name='cars')
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return self.license_plate


class ParkingSession(models.Model):
    car = models.ForeignKey(Car, on_delete=models.DO_NOTHING)
    parking_number = models.ForeignKey(ParkingSpace, on_delete=models.DO_NOTHING)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)
    tarif = models.ForeignKey(Pricing, null=True, blank=True, on_delete=models.DO_NOTHING, related_name='pricing')
    total_cost = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    end_session = models.BooleanField(default=False)

vision_park/recognize/forms.py
from django import forms


class ImageUploadForm(forms.Form):
    image = forms.ImageField()

vision_park/recognize/views.py
from django.utils import timezone
import os
import csv
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import resolve, reverse
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponseRedirect

from .forms import ImageUploadForm
from .models import Car, ParkingSession
from finance.models import Pricing
from parking_area.models import ParkingSpace

import cv2
from utils.datascience.main_yolo5 import yolo_predictions, net


@login_required
def main(request):
    resolved_view = resolve(request.path)
    active_menu = resolved_view.app_name
    return render(request, "recognize/main.html", {"active_menu": active_menu, "title": "Recognize"})


@login_required
def upload_out(request):
    resolved_view = resolve(request.path)
    active_menu = resolved_view.app_name
    context = {"active_menu": active_menu, "title": "CVM Recognize"}
    return render(request, "recognize/upload.html", context)

    return render(request, "recognize/upload_out.html", context)


@login_required
def upload_in(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                image_file = request.FILES['image']
                fs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'incoming'))
                filename = fs.save(image_file.name, image_file)

                image_path = fs.path(filename)
                img = cv2.imread(image_path)
                result_img, recognized_text = yolo_predictions(img, net)

                result_filename = 'processed_' + filename
                cv2.imwrite(os.path.join(fs.location, result_filename), result_img)
                result_img_url = fs.url('incoming/' + result_filename)

                thumbnail_size = (300, 200)
                thumbnail = cv2.resize(img, thumbnail_size, interpolation=cv2.INTER_AREA)
                thumbnail_filename = 'thumbnail_' + filename
                cv2.imwrite(os.path.join(fs.location, thumbnail_filename), thumbnail)
                thumbnail_image = fs.url('incoming/' + thumbnail_filename)

                return render(request, 'recognize/result_in.html', {
                    'recognized_area': result_img_url,
                    'recognized_image': thumbnail_image,
                    'recognized_text': recognized_text
                })
            except AttributeError:
                return render(request, 'recognize/result_in.html',
                              {'messages': ['The CV model could not recognize anything.'],
                               'recognized_area': '', 'recognized_image': '', 'recognized_text': ''})
    else:
        form = ImageUploadForm()
    return render(request, 'recognize/upload_in.html', {'form': form})


@login_required
def tariff_insert(request):
    tariff = Pricing.objects.filter(Q(end_time__isnull=True)).order_by('-start_time').first()
    if tariff:
        tariff_id = tariff.id
    else:
        default_tariff = Pricing.objects.get(id=1)
        tariff_id = default_tariff.id
    return tariff_id


@login_required
def create_parking_session(request):
    if request.method == 'POST':
        license_plate = request.POST.get('recognized_text')
        car, created = Car.objects.get_or_create(license_plate=license_plate)
        if car.is_blocked:
            messages.error(request, 'This Сar is not allowed to enter the parking\n"Ase of Base".')
            return render(request, 'recognize/result_in.html')

        active_session_exists = ParkingSession.objects.filter(car=car, end_session=False).exists()
        if active_session_exists:
            messages.error(request, 'The Parking Session for this Car is already open.')
            return render(request, 'recognize/result_in.html')

        parking_space = ParkingSpace.get_available_space()

        if parking_space:
            tarif_id = tariff_insert(request)
            parking_session = ParkingSession(car=car, parking_number=parking_space, tarif_id=tarif_id)
            parking_session.save()
            parking_space.is_occupied = True
            parking_space.save()

            return redirect(to='recognize:main')

        else:
            messages.error(request, 'No available parking space.')
            return render(request, 'recognize/result_in.html')

    else:
        return redirect('recognize:upload_in')


@login_required
def session_view(request):
    sessions_parking = ParkingSession.objects.filter(Q(end_session=False) | Q(car__is_blocked=True)
                                                     ).order_by('-start_time')[:20].select_related('car')
    return render(request, 'recognize/session_view.html', {'sessions_parking': sessions_parking})


@login_required
def session_action(request, pk):
    if request.method == 'POST':
        if request.user.is_superuser:
            if 'close_session' in request.POST:
                session_parking = get_object_or_404(ParkingSession.objects.select_related('tarif'), id=pk)
                parking_space = get_object_or_404(ParkingSpace, id=session_parking.parking_number_id)
                time_difference_minutes = (timezone.now() - session_parking.start_time).total_seconds() / 60

                if time_difference_minutes <= session_parking.tarif.free_period:
                    session_parking.end_session = True
                    parking_space.is_occupied = False
                    messages.success(request, 'Parking has been successfully completed.')
                else:
                    if session_parking.total_cost > 0:
                        time_outgoing_minutes = (timezone.now() - session_parking.end_time).total_seconds() / 60
                        if time_outgoing_minutes <= 5:
                            session_parking.end_session = True
                            parking_space.is_occupied = False
                            messages.success(request, 'Parking has been successfully completed.')
                        else:
                            session_parking.end_session = True
                            parking_space.is_occupied = False
                            messages.warning(request, 'Attention! checkout time limit exceeded.')
                    else:
                        messages.error(request, 'The free parking time has been exceeded.')

                session_parking.save()
                parking_space.save()

            elif 'unblock' in request.POST:
                session_parking = get_object_or_404(ParkingSession, id=pk)
                car = get_object_or_404(Car, id=session_parking.car.id)
                car.is_blocked = False
                car.save()
            elif 'ban' in request.POST:
                session_parking = get_object_or_404(ParkingSession, id=pk)
                car = get_object_or_404(Car, id=session_parking.car.id)
                car.is_blocked = True
                car.save()
            return HttpResponseRedirect(reverse('recognize:session_view'))
    return HttpResponseRedirect(reverse('recognize:session_view'))


def save_to_csv(user, object_data):
    current_date = datetime.now().strftime("%Y-%m-%d")
    filename = f"{user}-{current_date}.csv"
    file_path = settings.MEDIA_ROOT / filename

    with open(file_path, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile, delimiter=';')
        writer.writerow(['User', 'Email', 'Phone', 'License Plate', 'Status', 'Start parking',
                         'Number parkingplace', 'Tariff', 'Free Period', 'Payment', 'End parking',
                         'Close session'])
        for data in object_data:
            if data.car.owner:
                writer.writerow([data.car.owner, data.car.owner.email, data.car.owner.phone_number,
                                 data.car.license_plate, data.car.is_blocked, data.start_time, data.parking_number,
                                 data.tarif.name, data.tarif.free_period, data.total_cost, data.end_time,
                                 data.end_session])
            else:
                writer.writerow(["", "", "",
                                 data.car.license_plate, data.car.is_blocked, data.start_time, data.parking_number,
                                 data.tarif.name, data.tarif.free_period, data.total_cost, data.end_time,
                                 data.end_session])

    return filename


@login_required
def download_csv(request):
    if request.method == 'POST':
        if request.user.is_superuser:
            if 'download_csv' in request.POST:
                sessions_parking = ParkingSession.objects.all().order_by('start_time').select_related('car')
                print(sessions_parking)
                filename = save_to_csv(request.user.username, sessions_parking)
                messages.success(request, f'The file {filename} was\nsuccessfully saved to the /media directory.')
            return HttpResponseRedirect(reverse('recognize:session_view'))
    return HttpResponseRedirect(reverse('recognize:session_view'))

vision_park/recognize/templates/recognize/main.html
{% extends "vision_park/base.html" %}

{% block title %}
Recognize
{% endblock %}

{% block content %}
{% load static %}
<div class="container">

    <div class="row justify-content-center" style="margin-top: 50px;">
        <div class="col-md-6 d-flex align-items-center">
            <a href="{% url 'recognize:upload_in' %}" class="btn btn-lg btn-block">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                            <img src="{% static 'img/logo-compressed2.jpg' %}" alt="Placeholder image"/>
                        </figure>

                    </div>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-3">Upload photo of car for enter</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>


        <div class="col-md-6 d-flex align-items-center">
            <div class="card-body mx-auto text-center">
                <a href="{% url 'recognize:session_view' %}" class="btn btn-lg btn-block">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src="{% static 'img/logo-compressed3.jpg' %}" alt="Placeholder image"/>
                            </figure>

                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    <p class="title is-3">Preprocessing of car for exit</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

vision_park/recognize/templates/recognize/result_in.html
{% extends "vision_park/base.html" %}

{% block title %}
Result Recognized
{% endblock %}

{% block content %}
{% load static %}

{% if user.is_superuser %}
<h2 class="title is-2">Result Recognized Incoming Auto</h2>
<form method="post" action="{% url 'recognize:result_in' %}">
  {% csrf_token %}
  <div class="container" id="photo_result">
    <table class="table">
      <tbody>
        <tr>
          <th>Recognized Area:</th>
          <td>{{ recognized_area }}</td>
        </tr>
         <tr>
          <th>Recognized Image:</th>
          <td><img src="{{ recognized_image }}"> </td>
        </tr>
        <tr>
          <th>Recognized Number:</th>
          <td>{{ recognized_text }}</td>
        </tr>
        <tr>
          <th><button class="button is-link" style="background: #125C13" type="submit">Update License Plate</button></th>
          <td><input type="text" name="recognized_text" value="{{ recognized_text }}" maxlength="20"></td>
        </tr>
      </tbody>
    </table>
  </div>
  {% if messages %}
{% for message in messages %}
<article class="message is-danger">
  <div class="message-body">
{{ message }}
  </div>
</article>
{% endfor %}
  {% endif %}


</form>
{% else %}
<div class="p-2 bg-danger text-white">Recognize denied</div>
{% endif %}

{% endblock content %}

vision_park/recognize/templates/recognize/session_view.html
{% extends "vision_park/base.html" %}

{% block title %}
List All Parking Sessions
{% endblock %}

{% block content %}
{% load static %}

<div class="container" style=" margin-top: 30px;">
{% if user.is_superuser %}

<h2 class="title is-2">List All Parking Sessions</h2>

<br>
<table class="table">
    <tr>
    <tr>
        <th colspan="2">For download all parking sessions click</th>
    </tr>
    <tr>
        <th>
            <form method="post" action="{% url 'recognize:download_csv' %}"
                  name="download_csv">
                {% csrf_token %}
                <input class="btn btn-secondary" type="hidden" name="download_csv" value="download_csv">
                <button class="btn btn-secondary" type="submit">Save as CSV</button>
            </form>
        </th>
    </tr>
    </tr>
</table>
<br>
{% if sessions_parking %}
<table class="table">
    <tr>
        <th>User</th>
        <th>License Plate</th>
        <th>Status</th>
        <th>Start parking</th>
        <th>Number parkingplace</th>
        <th>Payment</th>
        <th>End parking</th>
        <th>Close session</th>
        <th>Actions</th>
    </tr>
    {% for session_parking in sessions_parking %}
    <tr>
        <td>{{ session_parking.car.owner }}</td>
        <td>{{ session_parking.car.license_plate }}</td>
        <td>{% if session_parking.car.is_blocked %}Blocked{% else %}Unblocked{% endif %}</td>
        <td>{{ session_parking.start_time }}</td>
        <td>{{ session_parking.parking_number }}</td>
        <td>{{ session_parking.total_cost }}</td>
        <td>{{ session_parking.end_time|default:"" }}</td>
        <td>
            {% if not session_parking.end_session %}
            <form method="post" action="{% url 'recognize:session_action' session_parking.id %}"
                  name="close_session">
                {% csrf_token %}
                <input type="hidden" name="close_session" value="close_session">
                <button class="button is-warning" type="submit">Close session</button>
            </form>
            {% else %}
            {{ session_parking.end_session }}
            {% endif %}
            </td>
        <td>

            {% if session_parking.car.is_blocked %}
            <form method="post" action="{% url 'recognize:session_action' session_parking.id %}"
                  name="unblock">
                {% csrf_token %}
                <input type="hidden" name="unblock" value="unblock">
                <button class="button is-link" style="background: #125C13" type="submit">Unblock</button>
            </form>
            {% else %}
            <form method="post" action="{% url 'recognize:session_action' session_parking.id %}"
                  name="ban">
                {% csrf_token %}
                <input type="hidden" name="ban" value="ban">
                <button class="button is-danger" type="submit">Ban</button>
            </form>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
    <h3 class="title is-3">There are no data</h3>
{% endif %}



{% for message in messages %}
<article class="message is-primary">
  <div class="message-body">
{{ message }}
  </div>
</article>
{% endfor %}

</div>

{% else %}
<div class="p-2 bg-danger text-white">Recognize denied</div>
{% endif %}

{% endblock content %}

vision_park/recognize/templates/recognize/upload.html
<!-- photos/templates/upload.html -->
{% extends "vision_park/base.html" %} {% block content %} {% if target_type %}
<h1>Upload photo: {{ target_type.desc}}</h1>
{% else %}
<h1>Upload photo</h1>
{% endif %}
<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %} {% if form.errors %}
  <ul class="text-danger">
    {% for field_name, error_list in form.errors.items %} {% for error in error_list %}
    <li>{{ error }}</li>
    {% endfor %} {% endfor %}
  </ul>
  {% endif %}
  <p {% if target_type %} class="d-none" {% endif %}>{{ form.type.label_tag }} {{ form.t_photo }}</p>
  {% if target_type.desc == "OUT" %}
  <p>{{ form.registration_id.label_tag }} {{ form.registration_id }}</p>
  {% if form.registration_id.errors %}
  <p class="text-danger">{{ form.registration_id.errors }}</p>
  {% endif %}
  <p>{{ form.manual_registration_id.label_tag }} {{ form.manual_registration_id }}</p>
  {% if form.manual_registration_id.errors %}
  <p class="text-danger">{{ form.manual_registration_id.errors }}</p>
  {% endif %} {% endif %} 
  <p>{{ form.photo.label_tag }} {{ form.photo }}</p>
  
  {% if target_type.desc == "OUT" %}
  <div class="alert alert-info" role="alert">
    You can leave only if you have paid the parking service invoice or if you have 0.00 to pay.
  </div>
  {% endif %}
  <div class="container">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">
        <input class="btn btn-primary" type="submit" value="Submit" />
      </li>
      <li class="list-group-item">
        <a href="{% url 'recognize:main' %}" class="btn btn-primary">Back</a>
      </li>
      {% if target_type.desc == "OUT" %}
      <li class="list-group-item">
        <a href="#" class="btn btn-primary">Pay</a>
      </li>
      {% endif %}
    </ul>
  </div>
</form>
<p></p>

{% endblock content %}

vision_park/recognize/templates/recognize/upload_in.html
{% extends "vision_park/base.html" %}
{% block title %}
Car For Enter
{% endblock %}

{% block content %}

{% if user.is_superuser %}
<h2 class="title is-2">Upload photo of car for enter</h2>
<form method="post" enctype="multipart/form-data" style="margin-top: 30px; margin-left: 20px;">
  {% csrf_token %}
 {{ form.as_p }}
  <p>{{ form.photo.label_tag }} {{ form.photo }}</p>
  <div class="field is-grouped" style="margin-top: 20px">
    <div class="control">
      <button class="button is-link" style="background: #125C13" type="submit">Submit</button>
    </div>
    <div class="control">
      <a class="button is-link is-light" style="background: #d9e7ce; color: #333333" href="{% url 'recognize:main' %}"
         class="btn btn-primary">Back</a>
    </div>
  </div>
</form>

{% else %}
<div class="p-2 bg-danger text-white">Recognize denied</div>
{% endif %}

{% endblock content %}