vision_park/accounts/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/', views.profile_add_car, name='profile'),
    path('profile/delete/<int:pk>/', views.profile_action, name='profile_action'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                          success_url='/auth/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

vision_park/finance/urls.py
from django.urls import path
from . import views

app_name = "finance"

urlpatterns = [
    path('payments-user/', views.payments_user, name='payments_user'),
    path('payment-preview/<int:session_id>/', views.payment_preview, name='payment_preview'),
    path('payment-confirm/<int:session_id>/', views.payment_confirm, name='payment_confirm'),
    path('tariffs/', views.tariffs, name='tariffs'),
    path('tariff-add/', views.tariff_add, name='tariff_add'),
    path('tariff-complete/<int:tariff_id>', views.tariff_complete, name='tariff_complete'),
]

vision_park/vision_park/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_control
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve

from . import views
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('auth/', include('accounts.urls')),
    path('parking_area/', include('parking_area.urls')),
    path('recognize/', include('recognize.urls')),
    path('finance/', include('finance.urls')),
] + static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve)) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vision_park/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    username = models.CharField(max_length=32, blank=False, unique=True)
    email = models.EmailField(max_length=64, blank=False, unique=True)
    phone_number = models.CharField(null=True, unique=True)
    telegram_nickname = models.CharField(max_length=32, blank=True, unique=True)

    def __str__(self):
        return self.username

vision_park/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput, forms
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy

User = get_user_model()


class RegisterForm(UserCreationForm):
    username = CharField(max_length=32, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=64, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    phone_number = forms.CharField(max_length=13, min_length=13, required=True,
                                   widget=forms.TextInput(
                                       attrs={'placeholder': '+380XXXXXXXXX', "class": "form-control"}))
    telegram_nickname = forms.CharField(max_length=32, required=False,
                                        widget=forms.TextInput(
                                            attrs={'placeholder': '@nickname', "class": "form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'phone_number', 'telegram_nickname', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This e-mail address is already in use.')
        return email

    def clean_telegram_nickname(self):
        telegram_nickname = self.cleaned_data.get('telegram_nickname')
        if telegram_nickname:
            if not telegram_nickname.startswith('@'):
                telegram_nickname = '@' + telegram_nickname
            if User.objects.filter(telegram_nickname=telegram_nickname).exists():
                self.add_error('telegram_nickname',
                               ValidationError(gettext_lazy('This telegram nickname is already in use.'),
                                               code='invalid'))
        return telegram_nickname


class LoginForm(AuthenticationForm):
    username = CharField(max_length=32, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')

vision_park/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import RegisterForm, LoginForm
from recognize.models import Car, ParkingSession


class RegisterView(View):
    template_name = 'accounts/registration.html'
    register_form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="main")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"title": "Register new user",
                                                    "register_form": self.register_form_class})

    def post(self, request):
        register_form = self.register_form_class(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            username = register_form.cleaned_data["username"]
            messages.success(request, f"Congratulations " + username + "! Your account has been successfully created!")
            return redirect(to="main")
        return render(request, self.template_name, {"register_form": register_form})


class LoginView(View):
    template_name = 'accounts/login.html'
    form_class = LoginForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="main")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, f"Nice to see you {user.username}!")
            return redirect(to="main")
        return render(request, self.template_name, {"form": form})


class LogoutView(View):
    def get(self, request):
        username = request.user.username
        logout(request)
        return render(request, "accounts/logout.html", {"title": "Logout user", "username": username})
        # redirect(to="main")


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    try:
        template_name = 'accounts/password_reset.html'
        email_template_name = 'accounts/password_reset_email.html'
        html_email_template_name = 'accounts/password_reset_email.html'
        success_url = reverse_lazy('accounts:password_reset_done')
        success_message = "An email with instructions to reset your password has been sent to %(email)s."
        subject_template_name = 'accounts/password_reset_subject.txt'
    except Exception as err:
        print(f"Error sending email: {err}")


@login_required
def profile_add_car(request):
    if request.method == 'POST':
        if 'add_license_plate' in request.POST:
            car_license_plate = request.POST.get('add_license_plate')
            car = Car.objects.get(license_plate=car_license_plate)
            car.owner_id = request.user.id
            car.save()
            return redirect(to='accounts:profile')
        else:
            return HttpResponseRedirect(reverse('accounts:profile'))
    else:
        user_cars = Car.objects.filter(owner=request.user)
        available_cars = Car.objects.filter(owner__isnull=True)
        context = {'user_profile': request.user, 'user_cars': user_cars,
                   'available_cars': available_cars}
        return render(request, 'accounts/profile_add_cars.html', context)


@login_required
def profile_action(request, pk):
    if request.method == 'POST':
        if 'delete_license_plate' in request.POST:
            try:
                car = get_object_or_404(Car, id=pk)
                car_session_parking = ParkingSession.objects.filter(car_id=pk, total_cost__gt=0).exists()
                if car_session_parking:
                    messages.error(request, 'Payment has already been registered for this car number.')
                else:
                    car.owner = None
                    car.save()
            except Car.DoesNotExist:
                messages.error(request, 'Car does not exist.')
            return redirect('accounts:profile')
        else:
            return redirect('accounts:profile')
    else:
        return redirect('accounts:profile')

vision_park/accounts/templates/accounts/login.html
{% extends "vision_park/base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
<h2 class="title is-2" style="width: 50%">Login</h2>

{% if messages %}
{% for message in messages %}
<article class="message is-danger">
    <div class="message-body">
        {{ message }}
    </div>
</article>
{% endfor %}
{% endif %}

{% if form.errors %}
<article class="message is-danger">
    <div class="message-body">
        {{ form.non_field_errors}}
    </div>
</article>
{% endif %}

<form class="field" style="width: 50%" method="post">
    {% csrf_token %}

    <label class="label">Username</label>
    {{form.username}}

    <label style="margin-top: 20px" class="label" for="free_period">Password</label>
    {{form.password}}

    <div class="field is-grouped" style="margin-top: 20px">
        <div class="control">
            <button class="button is-link" style="background: #125C13" type="submit">Confirm</button>
        </div>
    </div>
    <div class="small">
        <a style="color: #333333" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
    </div>
</form>
{% endblock %}

vision_park/accounts/templates/accounts/logout.html
{% extends "vision_park/base.html" %}

{% block title %}
Logout
{% endblock %}

{% block content %}

<article class="message is-info" style="margin-top: 25px">
    <div class="message-body">
        Time is tickin away...<br>
        Goodbye!<br>
        We will be glad to see You again!
    </div>
</article>

{% endblock %}

vision_park/accounts/templates/accounts/password_reset.html
{% extends "vision_park/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

vision_park/accounts/templates/accounts/password_reset_complete.html
{% extends "parking/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

vision_park/accounts/templates/accounts/password_reset_confirm.html
{% extends "parking/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

vision_park/accounts/templates/accounts/password_reset_done.html
{% extends "vision_park/base.html" %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<h2>Password reset request sent.</h2>
<p>We've emailed You with instructions on how to reset your password.</p>

{% endblock %}

vision_park/accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account.<br>Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">
        Reset password
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Vision Park Team</p>
{% endautoescape %}

vision_park/accounts/templates/accounts/profile_add_cars.html
{% extends "vision_park/base.html" %}

{% block title %}
Profile
{% endblock %}

{% block content %}

{% if form.errors %}
<div style="width: 25%;" class="alert alert-danger" role="alert">
    {{ form.non_field_errors}}
</div>
{% endif %}

<h2 class="title is-2">Profile</h2>
<div class="container" id="photo_result">
    <table class="table">
        <tbody>
        <tr>
            <th>Username:</th>
            <td>{{ user_profile.username }}</td>
        </tr>
        <tr>
            <th>E-mail Address:</th>
            <td>{{ user_profile.email }}</td>
        </tr>
        <tr>
            <th>Phone Number:</th>
            <td>
                {{ user_profile.phone_number }}
            </td>
        </tr>
        <tr>
            <th>Telegram Alias:</th>
            <td>
                <a type="button" class="btn btn-primary"
                   href="https://t.me/VisionPark_bot?start={{ user_profile.username }}"><i class="bi bi-telegram"></i>
                    Start</a>
                {{ user_profile.telegram_nickname }}
            </td>
        </tr>
        </tbody>
    </table>
    <br>

    {% if available_cars %}

    <form method="post" action="{% url 'accounts:profile' %}" name="add_license_plate">
        {% csrf_token %}

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors}}
        </div>
        {% endif %}


        <select name="add_license_plate" style="height: 40px; border-radius: 5px; width: 10%; margin-right: 20px">
            {% for car in available_cars %}
            <option value="{{ car.license_plate }}">{{ car.license_plate }}</option>
            {% empty %}
            <option value="">No available cars</option>
            {% endfor %}
        </select>


        <button type="submit" class="button is-link" style="background: #125C13">Add My License Plate
        </button>
    </form>

    {% endif %}


    <h2 class="title is-2">User cars</h2>
    {% if user_cars %}
    <table class="table is-fullwidth">
        <thead>
        <tr>
            <th>Number plate</th>
            <th>Block status</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for car in user_cars %}
        <tr>
            <td>{{ car.license_plate }}</td>
            <td>{% if car.is_blocked %}Blocked{% else %}Unblocked{% endif %}</td>
            <td>
                <form method="post" action="{% url 'accounts:profile_action' car.id %}"
                      name="delete_license_plate">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="hidden" name="delete_license_plate"
                           value="delete_license_plate">
                    <button class="button is-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


    {% else %}
    <h3 class="title is-3">User has no cars</h3>
    {% endif %}

    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} style="width: 25%;" class="alert alert-{{message.tags}}" {% endif %} role="alert">
        {{message}}
    </div>
    {% endfor %}
    {% endif %}

</div>
{% endblock %}

vision_park/accounts/templates/accounts/registration.html
{% extends "vision_park/base.html" %}

{% block title %}
Registration
{% endblock %}

{% block content %}
<h2 class="title is-2" style="width: 50%">Registration</h2>

{% if messages %}
{% for message in messages %}
<article class="message is-danger">
    <div class="message-body">
        {{ message }}
    </div>
</article>
{% endfor %}
{% endif %}

{% if form.errors %}
<article class="message is-danger">
    <div class="message-body">
        {{ form.non_field_errors}}
    </div>
</article>
{% endif %}

<form class="field" style="width: 50%" method="post">
    {% csrf_token %}

    <label class="label">Username</label>
    {{ register_form.username }}
    <span>{{ register_form.errors.username }}</span>

    <label style="margin-top: 20px"  class="label">Email</label>
    {{ register_form.email }}
    <span>{{ register_form.errors.email }}</span>

    <label style="margin-top: 20px"  class="label">Phone number</label>
    {{ register_form.phone_number }}
    <span>{{ register_form.errors.phone_number }}</span>

    <label style="margin-top: 20px"  class="label">Telegram</label>
    {{ register_form.telegram_nickname }}
    <span>{{ register_form.errors.telegram_nickname }}</span>

    <label style="margin-top: 20px"  class="label">Password</label>
    {{ register_form.password1 }}
    <span>{{ register_form.errors.password1 }}</span>

    <label style="margin-top: 20px"  class="label">Confirm password</label>
    {{ register_form.password2 }}
    <span>{{ register_form.errors.password2 }}</span>

    <div class="field is-grouped" style="margin-top: 20px">
        <div class="control">
            <button class="button is-link" style="background: #125C13" type="submit">Sign Up</button>
        </div>
    </div>
</form>
{% endblock %}